# -*- coding: utf-8 -*-
"""Penerjemah Manga Projek.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JASA-D6KZ-prlZn28_94AJr9LyU_Sodh

# Project Translator Manga v1
"""

!pip install manga-ocr

import PIL.Image

from manga_ocr import MangaOcr

mocr = MangaOcr()

img = PIL.Image.open('/content/ballon.png')
text = mocr(img)

text

"""---------------------------"""

!pip install googletrans==4.0.0-rc1

from googletrans import Translator

def translate_japanese_to_indonesian(text):
    translator = Translator()
    translated_text = translator.translate(text, src='ja', dest='id')
    return translated_text.text

# Contoh penggunaan
japanese_text = text
translated_text = translate_japanese_to_indonesian(japanese_text)

print(f"Jepang: {japanese_text}")
print(f"Indonesia: {translated_text}")